=== MATTYOneInc/AionEncomBase/data/static_data/minions/minions.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../modifiers.xsd"/>
	<xs:element name="minions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="minion" type="Minion" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Minion">
		<xs:sequence>
			<xs:element name="physical_attr" type="MinionStatAttribute" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="magical_attr" type="MinionStatAttribute" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="nameid" type="xs:int"/>
		<xs:attribute name="group_set" type="xs:string"/>
		<xs:attribute name="tier_grade" type="xs:string"/>
		<xs:attribute name="star_grade" type="xs:int"/>
		<xs:attribute name="is_only_feeds" type="xs:boolean"/>
		<xs:attribute name="use_func_option" type="xs:boolean"/>
		<xs:attribute name="skill01" type="xs:int"/>
		<xs:attribute name="skill01_energy" type="xs:int"/>
		<xs:attribute name="skill02" type="xs:int" use="optional"/>
		<xs:attribute name="skill02_energy" type="xs:int" use="optional"/>
		<xs:attribute name="iserect" type="xs:int" use="optional"/>
		<xs:attribute name="walk" type="xs:float" use="optional"/>
		<xs:attribute name="run" type="xs:float" use="optional"/>
		<xs:attribute name="height" type="xs:float" use="optional"/>
		<xs:attribute name="alti" type="xs:float" use="optional"/>
		<xs:attribute name="max_growth_value" type="xs:int" use="optional"/>
		<xs:attribute name="growth_pt" type="xs:int" use="optional"/>
		<xs:attribute name="growth_cost" type="xs:int" use="optional"/>
		<xs:attribute name="evolve_item" type="xs:int" use="optional"/>
		<xs:attribute name="evolve_item_num" type="xs:int" use="optional"/>
		<xs:attribute name="evolve_cost" type="xs:int" use="optional"/>
	</xs:complexType>
	<xs:complexType name="MinionStatAttribute">
		<xs:attribute name="stat" type="modifiersenum" use="required"/>
		<xs:attribute name="func" type="StatFunc" use="required"/>
		<xs:attribute name="value" type="xs:int" use="required"/>
	</xs:complexType>
</xs:schema>

=== MATTYOneInc/AionEncomBase/data/static_data/minions/minions.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<minions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="minions.xsd">
    <minion id="980010" name="Kerubim" nameid="1614348" group_set="TESTFAMILIARGROUP02" tier_grade="D" star_grade="1" is_only_feeds="true" use_func_option="false" skill01="4909" skill01_energy="48" iserect="1" walk="1.132" run="6.0" height="1.20" growth_pt="10">
        <physical_attr stat="MAXHP" func="ADD" value="50"/>
        <magical_attr stat="MAXHP" func="ADD" value="50"/>
    </minion>
    <minion id="980011" name="Kerubian" nameid="1614350" group_set="TESTFAMILIARGROUP09" tier_grade="C" star_grade="1" is_only_feeds="true" use_func_option="false" skill01="4908" skill01_energy="48" iserect="1" walk="1.132" run="6.0" height="1.20" growth_pt="100">
        <physical_attr stat="MAXHP" func="ADD" value="100"/>
        <physical_attr stat="PHYSICAL_ATTACK" func="ADD" value="1"/>
        <magical_attr stat="MAXHP" func="ADD" value="100"/>
        <magical_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="6"/>
    </minion>
    <minion id="980012" name="Kerubiel" nameid="1614352" group_set="TESTFAMILIARGROUP10" tier_grade="B" star_grade="1" is_only_feeds="true" use_func_option="false" skill01="4907" skill01_energy="48" iserect="1" walk="1.132" run="6.0" height="1.20" growth_pt="1300">
        <physical_attr stat="MAXHP" func="ADD" value="110"/>
        <physical_attr stat="PHYSICAL_ATTACK" func="ADD" value="1"/>
        <physical_attr stat="PHYSICAL_CRITICAL" func="ADD" value="3"/>
        <magical_attr stat="MAXHP" func="ADD" value="110"/>
        <magical_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="7"/>
        <magical_attr stat="MAGICAL_ACCURACY" func="ADD" value="4"/>
    </minion>
    <minion id="980013" name="Arch Kerubiel" nameid="1614354" group_set="TESTFAMILIARGROUP11" tier_grade="A" star_grade="1" is_only_feeds="true" use_func_option="false" skill01="4906" skill01_energy="48" iserect="1" walk="1.132" run="6.0" height="1.20" growth_pt="4000">
        <physical_attr stat="MAXHP" func="ADD" value="161"/>
        <physical_attr stat="PHYSICAL_ATTACK" func="ADD" value="2"/>
        <physical_attr stat="PHYSICAL_CRITICAL" func="ADD" value="5"/>
        <physical_attr stat="PHYSICAL_ACCURACY" func="ADD" value="7"/>
        <magical_attr stat="MAXHP" func="ADD" value="161"/>
        <magical_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="11"/>
        <magical_attr stat="MAGICAL_ACCURACY" func="ADD" value="6"/>
        <magical_attr stat="MAGICAL_CRITICAL" func="ADD" value="4"/>
    </minion>
    <minion id="980020" name="Seiren" nameid="1614356" group_set="TESTFAMILIARGROUP03" tier_grade="C" star_grade="1" is_only_feeds="false" use_func_option="true" skill01="4902" skill01_energy="120" iserect="1" walk="1.132" run="6.0" height="1.2" alti="1.5" max_growth_value="2000" growth_pt="100" growth_cost="100000" evolve_item="190200000" evolve_item_num="10" evolve_cost="20000000">
        <physical_attr stat="MAXHP" func="ADD" value="104"/>
        <physical_attr stat="PHYSICAL_ATTACK" func="ADD" value="1"/>
        <magical_attr stat="MAXHP" func="ADD" value="104"/>
        <magical_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="6"/>
    </minion>
    <minion id="980021" name="Seiren" nameid="1614356" group_set="TESTFAMILIARGROUP03" tier_grade="C" star_grade="2" is_only_feeds="false" use_func_option="true" skill01="4903" skill01_energy="120" iserect="1" walk="1.132" run="6.0" height="1.2" alti="1.5" max_growth_value="2000" growth_pt="200" growth_cost="100000" evolve_item="190200000" evolve_item_num="20" evolve_cost="20000000">
        <physical_attr stat="MAXHP" func="ADD" value="116"/>
        <physical_attr stat="PHYSICAL_ATTACK" func="ADD" value="3"/>
        <magical_attr stat="MAXHP" func="ADD" value="116"/>
        <magical_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="14"/>
    </minion>
    <minion id="980022" name="Seiren" nameid="1614356" group_set="TESTFAMILIARGROUP03" tier_grade="C" star_grade="3" is_only_feeds="false" use_func_option="true" skill01="4903" skill01_energy="120" skill02="4904" skill02_energy="240" iserect="1" walk="1.132" run="6.0" height="1.2" alti="1.5" max_growth_value="2000" growth_pt="300" growth_cost="100000" evolve_item="190200000" evolve_item_num="40" evolve_cost="20000000">
        <physical_attr stat="MAXHP" func="ADD" value="128"/>
        <physical_attr stat="PHYSICAL_ATTACK" func="ADD" value="5"/>
        <magical_attr stat="MAXHP" func="ADD" value="128"/>
        <magical_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="22"/>
    </minion>
    <minion id="980023" name="Seiren" nameid="1614356" group_set="TESTFAMILIARGROUP03" tier_grade="C" star_grade="4" is_only_feeds="false" use_func_option="true" skill01="4903" skill01_energy="120" skill02="4905" skill02_energy="240" iserect="1" walk="1.132" run="6.0" height="1.2" alti="1.5" max_growth_value="2000" growth_pt="400" growth_cost="100000" evolve_item="190200000" evolve_item_num="80" evolve_cost="20000000">
        <physical_attr stat="MAXHP" func="ADD" value="140"/>
        <physical_attr stat="PHYSICAL_ATTACK" func="ADD" value="7"/>
        <magical_attr stat="MAXHP" func="ADD" value="140"/>
        <magical_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="30"/>
    </minion>
    <minion id="980030" name="Steel Rose" nameid="1614358" group_set="TESTFAMILIARGROUP04" tier_grade="C" star_grade="1" is_only_feeds="false" use_func_option="true" skill01="4898" skill01_energy="48" iserect="1" walk="1.132" run="6.0" height="1.2" alti="1.5" max_growth_value="2000" growth_pt="100" growth_cost="100000" evolve_item="190200000" evolve_item_num="10" evolve_cost="20000000">
        <physical_attr stat="MAXHP" func="ADD" value="104"/>
        <physical_attr stat="PHYSICAL_ATTACK" func="ADD" value="1"/>
        <magical_attr stat="MAXHP" func="ADD" value="104"/>
        <magical_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="6"/>
    </minion>
    <minion id="980031" name="Steel Rose" nameid="1614358" group_set="TESTFAMILIARGROUP04" tier_grade="C" star_grade="2" is_only_feeds="false" use_func_option="true" skill01="4899" skill01_energy="48" iserect="1" walk="1.132" run="6.0" height="1.2" alti="1.5" max_growth_value="2000" growth_pt="200" growth_cost="100000" evolve_item="190200000" evolve_item_num="20" evolve_cost="20000000">
        <physical_attr stat="MAXHP" func="ADD" value="116"/>
        <physical_attr stat="PHYSICAL_ATTACK" func="ADD" value="3"/>
        <magical_attr stat="MAXHP" func="ADD" value="116"/>
        <magical_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="14"/>
    </minion>
    <minion id="980032" name="Steel Rose" nameid="1614358" group_set="TESTFAMILIARGROUP04" tier_grade="C" star_grade="3" is_only_feeds="false" use_func_option="true" skill01="4899" skill01_energy="48" skill02="4900" skill02_energy="240" iserect="1" walk="1.132" run="6.0" height="1.2" alti="1.5" max_growth_value="2000" growth_pt="300" growth_cost="100000" evolve_item="190200000" evolve_item_num="40" evolve_cost="20000000">
        <physical_attr stat="MAXHP" func="ADD" value="128"/>
        <physical_attr stat="PHYSICAL_ATTACK" func="ADD" value="5"/>
        <magical_attr stat="MAXHP" func="ADD" value="128"/>
        <magical_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="22"/>
    </minion>
    <minion id="980033" name="Steel Rose" nameid="1614358" group_set="TESTFAMILIARGROUP04" tier_grade="C" star_grade="4" is_only_feeds="false" use_func_option="true" skill01="4899" skill01_energy="48" skill02="4901" skill02_energy="240" iserect="1" walk="1.132" run="6.0" height="1.2" alti="1.5" max_growth_value="2000" growth_pt="400" growth_cost="100000" evolve_item="190200000" evolve_item_num="80" evolve_cost="20000000">
        <physical_attr stat="MAXHP" func="ADD" value="140"/>
        <physical_attr stat="PHYSICAL_ATTACK" func="ADD" value="7"/>
        <magical_attr stat="MAXHP" func="ADD" value="140"/>
        <magical_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="30"/>
    </minion>
    <minion id="980040" name="Abija" nameid="1614360" group_set="TESTFAMILIARGROUP05" tier_grade="B" star_grade="1" is_only_feeds="false" use_func_option="true" skill01="4894" skill01_energy="48" iserect="1" walk="1.132" run="6.0" height="1.2" alti="1.5" max_growth_value="10000" growth_pt="1300" growth_cost="300000" evolve_item="190200000" evolve_item_num="75" evolve_cost="80000000">
        <physical_attr stat="MAXHP" func="ADD" value="110"/>
        <physical_attr stat="PHYSICAL_ATTACK" func="ADD" value="2"/>
        <physical_attr stat="PHYSICAL_CRITICAL" func="ADD" value="4"/>
        <magical_attr stat="MAXHP" func="ADD" value="110"/>
        <magical_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="10"/>
        <magical_attr stat="MAGICAL_ACCURACY" func="ADD" value="7"/>
    </minion>
    <minion id="980041" name="Abija" nameid="1614360" group_set="TESTFAMILIARGROUP05" tier_grade="B" star_grade="2" is_only_feeds="false" use_func_option="true" skill01="4895" skill01_energy="48" iserect="1" walk="1.132" run="6.0" height="1.2" alti="1.5" max_growth_value="10000" growth_pt="2600" growth_cost="300000" evolve_item="190200000" evolve_item_num="125" evolve_cost="80000000">
        <physical_attr stat="MAXHP" func="ADD" value="170"/>
        <physical_attr stat="PHYSICAL_ATTACK" func="ADD" value="6"/>
        <physical_attr stat="PHYSICAL_CRITICAL" func="ADD" value="12"/>
        <magical_attr stat="MAXHP" func="ADD" value="170"/>
        <magical_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="28"/>
        <magical_attr stat="MAGICAL_ACCURACY" func="ADD" value="17"/>
    </minion>
