=== MATTYOneInc/AionEncomBase/AL-Game/data/static_data/npc_drops/npc_drops.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../import.xsd"/>
	<xs:include schemaLocation="../global_types.xsd"/>
	<xs:element name="drop" type="drop"/>
	<xs:element name="drop_group" type="dropGroup"/>
	<xs:element name="npc_drop" type="npcDrop"/>
	<xs:element name="npc_drops" type="npcDropData"/>
	<xs:complexType name="npcDropData">
		<xs:sequence>
			<xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="npc_drop" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="npcDrop">
		<xs:sequence>
			<xs:element ref="drop_group" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="npc_id" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="dropGroup">
		<xs:sequence>
			<xs:element ref="drop" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="race" type="Race"/>
		<xs:attribute name="use_category" type="xs:boolean"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="drop">
		<xs:sequence/>
		<xs:attribute name="item_id" type="xs:int" use="required"/>
		<xs:attribute name="min_amount" type="xs:int" use="required"/>
		<xs:attribute name="max_amount" type="xs:int" use="required"/>
		<xs:attribute name="chance" type="xs:float" use="required"/>
		<xs:attribute name="no_reduce" type="xs:boolean"/>
		<xs:attribute name="eachmember" type="xs:boolean"/>
	</xs:complexType>
</xs:schema>

=== MATTYOneInc/AionEncomBase/data/static_data/npc_drops/301680000_Instance_Idgel Dome Landmark.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- sunbsn @2025 -->
<npc_drops xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="npc_drops.xsd">
	<!-- Bomb Chest -->
	<npc_drop npc_id="834168">
		<drop_group name="COMMON_RARE" use_category="true" race="PC_ALL">
			<drop item_id="164000413" chance="8.54" min_amount="1" max_amount="1" no_reduce="false" eachmember="false" name="Support Bomb"/>
			<drop item_id="164000413" chance="5.47" min_amount="1" max_amount="1" no_reduce="false" eachmember="false" name="Support Bomb"/>
		</drop_group>
	</npc_drop>
	<!-- Chained Bomb Chest -->
	<npc_drop npc_id="834169">
		<drop_group name="COMMON_RARE" use_category="true" race="PC_ALL">
			<drop item_id="164000414" chance="4.37" min_amount="1" max_amount="1" no_reduce="false" eachmember="false" name="Support Restraining Bomb"/>
			<drop item_id="164000414" chance="2.94" min_amount="1" max_amount="1" no_reduce="false" eachmember="false" name="Support Restraining Bomb"/>
		</drop_group>
	</npc_drop>
</npc_drops>
