=== MATTYOneInc/AionEncomBase/AL-Game/data/static_data/revive_start_points/instance_revive_start_points.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.1">
    <xs:include schemaLocation="../global_types.xsd"/>
    <xs:element name="instance_revive_start_points">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="instance_revive_start_point" type="InstanceStartPoints" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="InstanceStartPoints">
        <xs:attribute name="world_id" type="xs:int"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="x" type="xs:float"/>
        <xs:attribute name="y" type="xs:float"/>
        <xs:attribute name="z" type="xs:float"/>
        <xs:attribute name="h" type="xs:byte"/>
    </xs:complexType>
</xs:schema>

=== MATTYOneInc/AionEncomBase/AL-Game/data/static_data/revive_start_points/instance_revive_start_points.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	"Revive Instance Start Point"
	Made By (Encom)
 -->
<instance_revive_start_points xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="instance_revive_start_points.xsd">
	<!-- Nochsana Training Camp -->
	<instance_revive_start_point world_id="300030000" name="" x="513" y="668" z="331" h="0"/>
	<!-- Dark Poeta -->
	<instance_revive_start_point world_id="300040000" name="" x="1225.9075" y="419.7187" z="140.18988" h="0"/>
	<!-- Carpus Isle Storeroom -->
	<instance_revive_start_point world_id="300050000" name="" x="469.343" y="567.713" z="201.732" h="0"/>
	<!-- Sulfur Tree Nest -->
	<instance_revive_start_point world_id="300060000" name="" x="462.352" y="345.609" z="162.817" h="0"/>
	<!-- Hamate Isle Storeroom -->
	<instance_revive_start_point world_id="300070000" name="" x="503.740" y="395.700" z="94.3400" h="0"/>
	<!-- Left Wing Chamber -->
	<instance_revive_start_point world_id="300080000" name="" x="672.09576" y="606.1819" z="321.19" h="0"/>
	<!-- Right Wing Chamber -->
	<instance_revive_start_point world_id="300090000" name="" x="265.984" y="387.77493" z="103.24291" h="0"/>
	<!-- Steel Rake -->
	<instance_revive_start_point world_id="300100000" name="" x="234.7316" y="505.87134" z="948.6736" h="0"/>
	<!-- Grave Of Steel Storeroom -->
	<instance_revive_start_point world_id="300120000" name="" x="527.334" y="122.056" z="175.954" h="0"/>
	<!-- Twilight Battlefield Storeroom -->
	<instance_revive_start_point world_id="300130000" name="" x="527.334" y="122.056" z="175.954" h="0"/>
	<!-- Isle Of Roots Storeroom -->
	<instance_revive_start_point world_id="300140000" name="" x="527.334" y="122.056" z="175.954" h="0"/>
	<!-- Udas Temple -->
	<instance_revive_start_point world_id="300150000" name="" x="635.11" y="647.73" z="133.23" h="0"/>
	<!-- Lower Udas Temple -->
	<instance_revive_start_point world_id="300160000" name="" x="1145" y="283" z="115.53778" h="0"/>
	<!-- Beshmundir Temple -->
	<instance_revive_start_point world_id="300170000" name="" x="1480.8746" y="255.21692" z="243.45709" h="0"/>
	<!-- Taloc's Hollow -->
	<instance_revive_start_point world_id="300190000" name="" x="199.87788" y="212.72118" z="1098.889" h="0"/>
	<!-- Haramel -->
	<instance_revive_start_point world_id="300200000" name="" x="172.0000" y="20.0000" z="144.22" h="0"/>
	<!-- Abyssal Splinter -->
	<instance_revive_start_point world_id="300220000" name="" x="704.0000" y="153.0000" z="453.0000" h="0"/>
	<!-- Kromede's Trial -->
	<instance_revive_start_point world_id="300230000" name="" x="244.98566" y="244.14162" z="189.52058" h="0"/>
	<!-- Aturam Sky Fortress -->
	<instance_revive_start_point world_id="300240000" name="" x="555.591" y="536.1958" z="600.8177" h="59"/>
	<!-- [Event] Aturam Sky Fortress -->
	<instance_revive_start_point world_id="300241000" name="" x="555.591" y="536.1958" z="600.8177" h="59"/>
	<!-- Esoterrace -->
	<instance_revive_start_point world_id="300250000" name="" x="333.0000" y="437.0000" z="326.0000" h="0"/>
	<!-- Rentus Base -->
	<instance_revive_start_point world_id="300280000" name="" x="564.1755" y="595.86145" z="153.75" h="72"/>
	<!-- Steel Rake Cabin -->
	<instance_revive_start_point world_id="300460000" name="" x="235.97552" y="506.31268" z="948.6735" h="60"/>
	<!-- Sealed Danuar Mysticarium -->
	<instance_revive_start_point world_id="300480000" name="" x="179.34444" y="122.14083" z="231.28636" h="59"/>
	<!-- Tiamat Stronghold -->
	<instance_revive_start_point world_id="300510000" name="" x="1581.6545" y="1068.9741" z="492.00992" h="61"/>
	<!-- Dragon Lord Refuge -->
	<instance_revive_start_point world_id="300520000" name="" x="503.44748" y="524.0377" z="240.26653" h="0"/>
	<!-- The Eternal Bastion -->
	<instance_revive_start_point world_id="300540000" name="" x="743.9309" y="293.51474" z="233.71062" h="105"/>
	<!-- Shugo Imperial Tomb -->
	<instance_revive_start_point world_id="300560000" name="" x="152.62431" y="199.87366" z="538.4448" h="0"/>
	<!-- Ophidan Bridge -->
	<instance_revive_start_point world_id="300590000" name="" x="769.26154" y="558.7093" z="572.95386" h="118"/>
	<!-- Unstable Abyssal Splinter -->
	<instance_revive_start_point world_id="300600000" name="" x="704.0000" y="153.0000" z="453.0000" h="0"/>
	<!-- Raksang Ruins -->
	<instance_revive_start_point world_id="300610000" name="" x="851.6795" y="947.84424" z="1206.6846" h="69"/>
	<!-- Occupied Rentus Base -->
	<instance_revive_start_point world_id="300620000" name="" x="564.1755" y="595.86145" z="153.75" h="72"/>
	<!-- Anguished Dragon Lord's Refuge -->
	<instance_revive_start_point world_id="300630000" name="" x="503.44748" y="524.0377" z="240.26653" h="0"/>
	<!-- The Hexway -->
	<instance_revive_start_point world_id="300700000" name="" x="672.8951" y="606.1681" z="321.19" h="46"/>
	<!-- Infinity Shard -->
	<instance_revive_start_point world_id="300800000" name="" x="118.806206" y="115.75847" z="131.8584" h="21"/>
	<!-- Danuar Reliquary -->
	<instance_revive_start_point world_id="301110000" name="" x="255.30792" y="245.11589" z="241.87251" h="29"/>
	<!-- Sauro Supply Base -->
	<instance_revive_start_point world_id="301130000" name="" x="641.5419" y="176.81075" z="195.65363" h="28"/>
	<!-- Seized Danuar Sanctuary -->
	<instance_revive_start_point world_id="301140000" name="" x="388.0756" y="1185.9813" z="55.30134" h="0"/>
	<!-- Rukibuki Circus Troupe Camp -->
	<instance_revive_start_point world_id="301200000" name="" x="464.59558" y="566.6469" z="201.64261" h="2"/>
	<!-- Illuminary Obelisk -->
	<instance_revive_start_point world_id="301230000" name="" x="321.9613" y="323.62772" z="405.49997" h="35"/>
	<!-- Linkgate Foundry -->
	<instance_revive_start_point world_id="301270000" name="" x="359.55505" y="259.99792" z="311.36365" h="60"/>
	<!-- Lucky Ophidan Bridge -->
	<instance_revive_start_point world_id="301320000" name="" x="769.26154" y="558.7093" z="572.95386" h="118"/>
	<!-- Lucky Danuar Reliquary -->
	<instance_revive_start_point world_id="301330000" name="" x="255.30792" y="245.11589" z="241.87251" h="29"/>
	<!-- [Infernal] Danuar Reliquary -->
	<instance_revive_start_point world_id="301360000" name="" x="255.30792" y="245.11589" z="241.87251" h="29"/>
	<!-- [Infernal] Illuminary Obelisk -->
	<instance_revive_start_point world_id="301370000" name="" x="321.9613" y="323.62772" z="405.49997" h="35"/>
	<!-- Danuar Sanctuary -->
	<instance_revive_start_point world_id="301380000" name="" x="388.0756" y="1185.9813" z="55.30134" h="0"/>
	<!-- Drakenspire Depths -->
	<instance_revive_start_point world_id="301390000" name="" x="326.8173" y="183.01366" z="1687.2552" h="1"/>
	<!-- The Shugo Emperor's Vault -->
	<instance_revive_start_point world_id="301400000" name="" x="543.20166" y="294.48053" z="400.56976" h="23"/>
	<!-- Sealed Argent Manor -->
	<instance_revive_start_point world_id="301510000" name="" x="994.73615" y="1205.4276" z="65.640015" h="90"/>
	<!-- Drakenspire Depths [Quest] -->
	<instance_revive_start_point world_id="301520000" name="" x="326.8173" y="183.01366" z="1687.2552" h="1"/>
	<!-- Archives Of Eternity -->
	<instance_revive_start_point world_id="301540000" name="" x="755.08514" y="511.9180" z="468.99835" h="59"/>
	<!-- Cradle Of Eternity -->
	<instance_revive_start_point world_id="301550000" name="" x="1477.0000" y="774.0000" z="1035.0000" h="0"/>
	<!-- Trials Of Eternity -->
	<instance_revive_start_point world_id="301560000" name="" x="1235.5623" y="1026.647" z="761.1762" h="60"/>
	<!-- Archives Of Eternity [Quest] -->
	<instance_revive_start_point world_id="301570000" name="" x="1235.5623" y="1026.647" z="761.1762" h="60"/>
	<!-- Emperor Trillirunerk's Safe -->
	<instance_revive_start_point world_id="301590000" name="" x="543.20166" y="294.48053" z="400.56976" h="23"/>
	<!-- Adma's Fall -->
	<instance_revive_start_point world_id="301600000" name="" x="493.72937" y="468.32947" z="173.48601" h="49"/>
	<!-- Theobomos Test Chamber -->
	<instance_revive_start_point world_id="301610000" name="" x="214.2665" y="372.62207" z="202.84311" h="98"/>
	<!-- Drakenseer's Lair -->
	<instance_revive_start_point world_id="301620000" name="" x="275.50073" y="349.62302" z="336.4679" h="94"/>
	<!-- Contaminated Underpath -->
	<instance_revive_start_point world_id="301630000" name="" x="230.0000" y="169.0000" z="164.0000" h="60"/>
	<!-- IDEvent_Def -->
	<instance_revive_start_point world_id="301631000" name="" x="230.0000" y="169.0000" z="164.0000" h="60"/>
	<!-- IDEvent_Def_H -->
	<instance_revive_start_point world_id="301632000" name="" x="230.0000" y="169.0000" z="164.0000" h="60"/>
	<!-- Secret Munitions Factory -->
	<instance_revive_start_point world_id="301640000" name="" x="376.39178" y="282.3938" z="198.24043" h="72"/>
	<!-- Fallen Poeta -->
	<instance_revive_start_point world_id="301660000" name="" x="306.1794" y="911.2256" z="105.5561" h="46"/>
	<!-- Aether Mine [Quest] -->
	<instance_revive_start_point world_id="301690000" name="" x="323.85403" y="267.03787" z="259.2078" h="91"/>
	<!-- Mirash Sanctuary -->
	<instance_revive_start_point world_id="301720000" name="" x="770.8157" y="819.0407" z="518.875" h="90"/>
	<!-- Smoldering Fire Temple -->
	<instance_revive_start_point world_id="302000000" name="" x="149.47774" y="452.1278" z="141.4794" h="97"/>
	<!-- Fissure Of Oblivion -->
	<instance_revive_start_point world_id="302100000" name="" x="916.0000" y="461.0000" z="352.0000" h="0"/>
	<!-- [Opportunity] Fissure Of Oblivion -->
	<instance_revive_start_point world_id="302110000" name="" x="916.0000" y="461.0000" z="352.0000" h="0"/>
	<!-- Kumuki Cave -->
	<instance_revive_start_point world_id="302330000" name="" x="172.0000" y="20.0000" z="144.22" h="0"/>
	<!-- Bastion Of Souls -->
	<instance_revive_start_point world_id="302340000" name="" x="1183.3446" y="734.37006" z="433.22742" h="91"/>
	<!-- Karamatis A [Quest] -->
	<instance_revive_start_point world_id="310010000" name="" x="221.5725" y="249.4774" z="206.12137" h="27"/>
	<!-- Karamatis B [Quest] -->
